find_package(SDL2 REQUIRED)
find_package(SDL2_image REQUIRED)
include_directories(${SDL2_INCLUDE_DIR})
include_directories(${SDL2_IMAGE_INCLUDE_DIRS})
message(${SDL2_IMAGE_INCLUDE_DIRS})


# link against SDL2_LIBRARY_SET
message("SDL2_LIBRARY : ${SDL2_LIBRARY}")
message("SDL2_IMAGE_LIBRARIES : ${SDL2_IMAGE_LIBRARIES}")
set(SDL2_LIBRARY_SET ${SDL2_LIBRARY} ${SDL2_IMAGE_LIBRARIES})